saved

diff --git a/0x02-shell_redirections/sc b/0x02-shell_redirections/sc
--- a/0x02-shell_redirections/sc
+++ b/0x02-shell_redirections/sc
@@ -1,6 +1,10 @@
 #!/bin/bash
-echo "Enter file name:"
-read file_name
+if [ "$#" -ne 1 ]; then
+	echo "Error: You must provide a file name as an argument."
+	exit 1
+fi 
+file_name ="$1"
+
 chmod u+x $file_name
 git add .
 git commit -m $file_name
